base:
  env: uat
  nameOverride: user-service
  role:
    create: true
    rules:
      - apiGroups:
          - ""
          - apps
        resources:
          - pods
          - nodes
          - deployments
          - configmaps
          - secrets
        verbs:
          - get
          - list
          - watch
  roleBinding:
    create: true
    subjects:
      - kind: ServiceAccount
        name: default
  deployment:
    image:
      repository: akjamie/bookstore-user-service
    initContainers:
      - name: init
        image: eclipse-temurin:19-jre-alpine
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - "-c"
          - |
            echo 'Coping keystore file from /etc/secret to /etc/keystore.'
            cp /etc/secret/* /etc/keystore/
            chmod 755 -R /etc/keystore
            echo 'Completed Coping keystore file.'
        volumeMounts:
          - name: conf
            mountPath: /etc/keystore
#            subPath: rsa.key
          - name: jwt-rsa-keystore
            mountPath: /etc/secret
    envVar:
      - name: SPRING_PROFILES_ACTIVE
        value: k8s
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            key: "spring.datasource.username"
            name: db-secret
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: "spring.datasource.password"
            name: db-secret
      - name: JWT_KEY_PATH
        value: "file:/etc/keystore/rsa.key"
      - name: SECRET_NAME
        value: db-secret
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: "metadata.namespace"
      - name: CONFIG_MAP_NAME
        value: user-service-uat-cm
      - name: spring.cloud.bootstrap.enabled
        value: "true"
    args:
      - --spring.cloud.compatibility-verifier.enabled=false
    volumes:
      - name: jwt-rsa-keystore
        secret:
          secretName: jwt-rsa
          items:
            - key: rsa.key
              path: rsa.key
            - key: rsa.pem
              path: rsa.pem
      - name: user-service-cm
        configMap:
          name:
      - name: user-service-secret
        secret:
          secretName:
      - name: conf
        emptyDir: { }
    volumeMounts:
      - name: conf
        mountPath: /etc/keystore
#        subPath: rsa.key
    readinessProbe:
      httpGet:
        port: 8080
        path: /actuator/health
      failureThreshold: 3
      successThreshold: 1
      periodSeconds: 5
    livenessProbe:
      httpGet:
        port: 8080
        path: /actuator/health
      failureThreshold: 3
      successThreshold: 1
      periodSeconds: 5
    startupProbe:
      httpGet:
        port: 8080
        path: /actuator/health
      failureThreshold: 40
      successThreshold: 1
      periodSeconds: 10
    resources:
      limits:
        cpu: 500m
        memory: 360Mi
      requests:
        cpu: 100m
        memory: 128Mi
  service:
    create: true
    targetPort: 8080
  ingress:
    create: true
    hosts:
      - host: gw.it-meta.space
        paths:
          - path: /user-service/(.*)
            pathType: Prefix
            backend:
              serviceName:
              port: 80
    tls:
      - hosts:
          - gw.it-meta.space
        secretName: gw-tls
    rewrite:
      target: "/$1"
  configMap:
    create: true
    data:
      application.yaml: |-
        spring:
          datasource:
            url: jdbc:mysql://192.168.179.1:3306/iam?charset=utf8
          data:
            redis:
              host: redis-headless.default.svc.it-meta.space
              port: 6379
