{{- if .Values.configMap.create }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "base.fullname" . }}-cm
  labels:
    {{- include "base.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}

{{- end }}
