{{- if .Values.deployment.create }}
{{- $env := .Values.env -}}
{{- $fullname := include "base.fullname" . -}}
{{- $claimName := printf "%s-pvc" $fullname -}}
{{- $secretName := printf "%s-secret" $fullname -}}
{{- $configMapName := printf "%s-cm" $fullname -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}-deploy
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml .Values.deployment.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.deployment.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "base.serviceAccountName" . }}
      {{- with .Values.deployment.podSecurityContext}}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: app-log
          emptyDir: {}
      {{- if .Values.deployment.volumes }}
        {{- range .Values.deployment.volumes }}
        - name: {{ .name }}
          {{- if .persistentVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ default $claimName .persistentVolumeClaim.claimName }}
          {{- else if .secret }}
          secret:
            secretName: {{ default $secretName .secret.secretName }}
          {{- else if .configMap }}
          configMap:
            name: {{ default $configMapName .configMap.name }}
          {{- else if .hostPath }}
          hostPath:
            path: {{ .hostPath.path }}
            type: {{ .hostPath.type }}
          {{- else if .emptyDir }}
          emptyDir: {}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.deployment.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "base.name" . }}
          {{- with .Values.deployment.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{- if .Values.deployment.args }}
          args: {{ .Values.deployment.args }}
          {{- end }}
          {{- if .Values.deployment.envVar }}
          env:
          {{- range .Values.deployment.envVar }}
            {{- if or (and (eq .name "SPRING_PROFILES_ACTIVE") (eq .value nil)) (and (eq .name "SPRING_PROFILES_ACTIVE") (eq .value "")) }}
            - name: {{ .name }}
              {{- if or (eq $env "prd") (eq $env "prod") (eq $env "dr")}}
              value: prd
              {{- else }}
              value: {{ .value }}
              {{- end }}
            {{- else }}
            - name: {{ .name }}
            {{- end }}
            {{- if .value }}
              value: {{ .value | quote }}
            {{- end }}
            {{- if and .valueFrom .valueFrom.secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  {{- if or (eq .valueFrom.secretKeyRef.name nil) (eq .valueFrom.secretKeyRef.name "") }}
                  name: {{ $secretName }}
                  {{- else }}
                  name: {{ .valueFrom.secretKeyRef.name }}
                  {{- end }}
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
            {{- if and .valueFrom .valueFrom.fieldRef .valueFrom.fieldRef.fieldPath }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ .valueFrom.fieldRef.fieldPath }}
            {{- end }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- with .Values.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml .Values.deployment.tolerations | nindent 8 }}
      {{- end }}
{{- end }}