{{- if .Values.deployment.create }}
{{- $env := .Values.env -}}
{{- $fullname := include "base.fullname" . -}}
{{- $claimName := printf "%s-pvc" $fullname -}}
{{- $secretName := printf "%s-secret" $fullname -}}
{{- $configMapName := printf "%s-cm" $fullname -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}-deploy
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "base.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: app-log
          emptyDir: {}
      {{- if .Values.volumes }}
        {{- range .Values.volumes }}
        - name: {{ .name }}
          {{- if .persistentVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ default $claimName .persistentVolumeClaim.claimName }}
          {{- else if .secret }}
          secret:
            secretName: {{ default $secretName .secret.secretName }}
          {{- else if .configMap }}
          configMap:
            name: {{ default $configMapName .configMap.name }}
          {{- else if .hostPath }}
          hostPath:
            path: {{ .hostPath.path }}
            type: {{ .hostPath.type }}
          {{- else if .emptyDir }}
          emptyDir: {}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.envVar }}
          env:
          {{- range .Values.envVar }}
            {{- if or (and (eq .name "SPRING_PROFILES_ACTIVE") (eq .value nil)) (and (eq .name "SPRING_PROFILES_ACTIVE") (eq .value "")) }}
            - name: {{ .name }}
              {{- if or (eq $env "prd") (eq $env "prod") (eq $env "dr")}}
              value: prd
              {{- else }}
              value: {{ .value }}
              {{- end }}
            {{- else }}
            - name: {{ .name }}
            {{- end }}
            {{- if .value }}
              value: {{ .value | quote }}
            {{- end }}
            {{- if and .valueFrom .valueFrom.secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  {{- if or (eq .valueFrom.secretKeyRef.name nil) (eq .valueFrom.secretKeyRef.name "") }}
                  name: {{ $secretName }}
                  {{- else }}
                  name: {{ .valueFrom.secretKeyRef.name }}
                  {{- end }}
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}