{{- if .Values.role.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "base.roleName" . }}
{{/*  namespace: {{ default "default" .Values.namespace }}*/}}
rules:
  {{- toYaml .Values.role.rules | nindent 2 }}
{{- end }}