{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "base.fullname" . }}-svc
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}
  {{- end }}